// Code generated by protoc-gen-go. DO NOT EDIT.
// source: db_item.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DbItem struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DbItem) Reset()         { *m = DbItem{} }
func (m *DbItem) String() string { return proto.CompactTextString(m) }
func (*DbItem) ProtoMessage()    {}
func (*DbItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_7acb839e425208fc, []int{0}
}

func (m *DbItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DbItem.Unmarshal(m, b)
}
func (m *DbItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DbItem.Marshal(b, m, deterministic)
}
func (m *DbItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DbItem.Merge(m, src)
}
func (m *DbItem) XXX_Size() int {
	return xxx_messageInfo_DbItem.Size(m)
}
func (m *DbItem) XXX_DiscardUnknown() {
	xxx_messageInfo_DbItem.DiscardUnknown(m)
}

var xxx_messageInfo_DbItem proto.InternalMessageInfo

func (m *DbItem) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *DbItem) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type DbQueryParam struct {
	StartKey             []byte   `protobuf:"bytes,1,opt,name=StartKey,proto3" json:"StartKey,omitempty"`
	EndKey               []byte   `protobuf:"bytes,2,opt,name=EndKey,proto3" json:"EndKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DbQueryParam) Reset()         { *m = DbQueryParam{} }
func (m *DbQueryParam) String() string { return proto.CompactTextString(m) }
func (*DbQueryParam) ProtoMessage()    {}
func (*DbQueryParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_7acb839e425208fc, []int{1}
}

func (m *DbQueryParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DbQueryParam.Unmarshal(m, b)
}
func (m *DbQueryParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DbQueryParam.Marshal(b, m, deterministic)
}
func (m *DbQueryParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DbQueryParam.Merge(m, src)
}
func (m *DbQueryParam) XXX_Size() int {
	return xxx_messageInfo_DbQueryParam.Size(m)
}
func (m *DbQueryParam) XXX_DiscardUnknown() {
	xxx_messageInfo_DbQueryParam.DiscardUnknown(m)
}

var xxx_messageInfo_DbQueryParam proto.InternalMessageInfo

func (m *DbQueryParam) GetStartKey() []byte {
	if m != nil {
		return m.StartKey
	}
	return nil
}

func (m *DbQueryParam) GetEndKey() []byte {
	if m != nil {
		return m.EndKey
	}
	return nil
}

type DbItems struct {
	Items                []*DbItem `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DbItems) Reset()         { *m = DbItems{} }
func (m *DbItems) String() string { return proto.CompactTextString(m) }
func (*DbItems) ProtoMessage()    {}
func (*DbItems) Descriptor() ([]byte, []int) {
	return fileDescriptor_7acb839e425208fc, []int{2}
}

func (m *DbItems) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DbItems.Unmarshal(m, b)
}
func (m *DbItems) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DbItems.Marshal(b, m, deterministic)
}
func (m *DbItems) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DbItems.Merge(m, src)
}
func (m *DbItems) XXX_Size() int {
	return xxx_messageInfo_DbItems.Size(m)
}
func (m *DbItems) XXX_DiscardUnknown() {
	xxx_messageInfo_DbItems.DiscardUnknown(m)
}

var xxx_messageInfo_DbItems proto.InternalMessageInfo

func (m *DbItems) GetItems() []*DbItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*DbItem)(nil), "proto.DbItem")
	proto.RegisterType((*DbQueryParam)(nil), "proto.DbQueryParam")
	proto.RegisterType((*DbItems)(nil), "proto.DbItems")
}

func init() { proto.RegisterFile("db_item.proto", fileDescriptor_7acb839e425208fc) }

var fileDescriptor_7acb839e425208fc = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x49, 0x8a, 0xcf,
	0x2c, 0x49, 0xcd, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x06, 0x5c,
	0x6c, 0x2e, 0x49, 0x9e, 0x25, 0xa9, 0xb9, 0x42, 0x02, 0x5c, 0xcc, 0xde, 0xa9, 0x95, 0x12, 0x8c,
	0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x20, 0xa6, 0x90, 0x08, 0x17, 0x6b, 0x58, 0x62, 0x4e, 0x69, 0xaa,
	0x04, 0x13, 0x58, 0x0c, 0xc2, 0x51, 0x72, 0xe2, 0xe2, 0x71, 0x49, 0x0a, 0x2c, 0x4d, 0x2d, 0xaa,
	0x0c, 0x48, 0x2c, 0x4a, 0xcc, 0x15, 0x92, 0xe2, 0xe2, 0x08, 0x2e, 0x49, 0x2c, 0x2a, 0x41, 0x68,
	0x86, 0xf3, 0x85, 0xc4, 0xb8, 0xd8, 0x5c, 0xf3, 0x52, 0x40, 0x32, 0x10, 0x23, 0xa0, 0x3c, 0x25,
	0x3d, 0x2e, 0x76, 0x88, 0xad, 0xc5, 0x42, 0xca, 0x5c, 0xac, 0x60, 0x86, 0x04, 0xa3, 0x02, 0xb3,
	0x06, 0xb7, 0x11, 0x2f, 0xc4, 0x79, 0x7a, 0x10, 0xe9, 0x20, 0x88, 0x5c, 0x12, 0x1b, 0x58, 0xd0,
	0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x15, 0xc3, 0xbb, 0x36, 0xc4, 0x00, 0x00, 0x00,
}
