// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package network

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Type                 uint32   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	To                   uint64   `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	From                 uint64   `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	Term                 uint64   `protobuf:"varint,4,opt,name=term,proto3" json:"term,omitempty"`
	Index                uint64   `protobuf:"varint,5,opt,name=index,proto3" json:"index,omitempty"`
	Count                uint32   `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`
	Data                 []byte   `protobuf:"bytes,7,opt,name=Data,proto3" json:"Data,omitempty"`
	Text                 string   `protobuf:"bytes,8,opt,name=text,proto3" json:"text,omitempty"`
	ResultCode           uint32   `protobuf:"varint,9,opt,name=ResultCode,proto3" json:"ResultCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Message) GetTo() uint64 {
	if m != nil {
		return m.To
	}
	return 0
}

func (m *Message) GetFrom() uint64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *Message) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *Message) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Message) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Message) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Message) GetResultCode() uint32 {
	if m != nil {
		return m.ResultCode
	}
	return 0
}

type BatchMessage struct {
	Term                 uint64     `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Messages             []*Message `protobuf:"bytes,2,rep,name=Messages,proto3" json:"Messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BatchMessage) Reset()         { *m = BatchMessage{} }
func (m *BatchMessage) String() string { return proto.CompactTextString(m) }
func (*BatchMessage) ProtoMessage()    {}
func (*BatchMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *BatchMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchMessage.Unmarshal(m, b)
}
func (m *BatchMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchMessage.Marshal(b, m, deterministic)
}
func (m *BatchMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchMessage.Merge(m, src)
}
func (m *BatchMessage) XXX_Size() int {
	return xxx_messageInfo_BatchMessage.Size(m)
}
func (m *BatchMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BatchMessage proto.InternalMessageInfo

func (m *BatchMessage) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *BatchMessage) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "network.Message")
	proto.RegisterType((*BatchMessage)(nil), "network.BatchMessage")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xcd, 0x4e, 0xc3, 0x30,
	0x0c, 0x80, 0x95, 0xae, 0x5b, 0x37, 0xb3, 0x21, 0x14, 0x71, 0xf0, 0x09, 0x45, 0x3b, 0xe5, 0x80,
	0x7a, 0x80, 0x37, 0x00, 0xae, 0x48, 0x28, 0x6f, 0x50, 0x36, 0xf3, 0x23, 0x68, 0x3d, 0x25, 0x9e,
	0x18, 0x8f, 0xc8, 0x5b, 0xa1, 0x38, 0xd5, 0xd4, 0xdb, 0xe7, 0xcf, 0x3f, 0x71, 0x0c, 0x9b, 0x9e,
	0x52, 0xea, 0xde, 0xa9, 0x3d, 0x44, 0x16, 0xb6, 0xcd, 0x40, 0xf2, 0xc3, 0xf1, 0x6b, 0xfb, 0x67,
	0xa0, 0x79, 0x2e, 0x29, 0x6b, 0xa1, 0x96, 0xdf, 0x03, 0xa1, 0x71, 0xc6, 0x6f, 0x82, 0xb2, 0xbd,
	0x84, 0x4a, 0x18, 0x2b, 0x67, 0x7c, 0x1d, 0x2a, 0xe1, 0x5c, 0xf3, 0x16, 0xb9, 0xc7, 0x99, 0x1a,
	0x65, 0xed, 0xa3, 0xd8, 0x63, 0x5d, 0x5c, 0x66, 0x7b, 0x0d, 0xf3, 0xcf, 0x61, 0x4f, 0x27, 0x9c,
	0xab, 0x2c, 0x41, 0xb6, 0x3b, 0x3e, 0x0e, 0x82, 0x0b, 0x7d, 0xa2, 0x04, 0xb9, 0xff, 0xa9, 0x93,
	0x0e, 0x1b, 0x67, 0xfc, 0x3a, 0x28, 0x97, 0x99, 0x27, 0xc1, 0xa5, 0x33, 0x7e, 0x15, 0x94, 0xed,
	0x0d, 0x40, 0xa0, 0x74, 0xfc, 0x96, 0x47, 0xde, 0x13, 0xae, 0x74, 0xc4, 0xc4, 0x6c, 0x5f, 0x60,
	0xfd, 0xd0, 0xc9, 0xee, 0x63, 0xfa, 0x9f, 0xbc, 0x97, 0x99, 0xec, 0x75, 0x0b, 0xcb, 0x31, 0x9d,
	0xb0, 0x72, 0x33, 0x7f, 0x71, 0x77, 0xd5, 0x8e, 0xb7, 0x68, 0xc7, 0x44, 0x38, 0x57, 0xbc, 0x2e,
	0xf4, 0x5a, 0xf7, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x1b, 0x90, 0x90, 0x3e, 0x01, 0x00,
	0x00,
}
