// Code generated by protoc-gen-go. DO NOT EDIT.
// source: collection_message.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Collection struct {
	Content              []*ObjectItem `protobuf:"bytes,1,rep,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Collection) Reset()         { *m = Collection{} }
func (m *Collection) String() string { return proto.CompactTextString(m) }
func (*Collection) ProtoMessage()    {}
func (*Collection) Descriptor() ([]byte, []int) {
	return fileDescriptor_24f70eda5f2a872a, []int{0}
}

func (m *Collection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Collection.Unmarshal(m, b)
}
func (m *Collection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Collection.Marshal(b, m, deterministic)
}
func (m *Collection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Collection.Merge(m, src)
}
func (m *Collection) XXX_Size() int {
	return xxx_messageInfo_Collection.Size(m)
}
func (m *Collection) XXX_DiscardUnknown() {
	xxx_messageInfo_Collection.DiscardUnknown(m)
}

var xxx_messageInfo_Collection proto.InternalMessageInfo

func (m *Collection) GetContent() []*ObjectItem {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*Collection)(nil), "proto.Collection")
}

func init() { proto.RegisterFile("collection_message.proto", fileDescriptor_24f70eda5f2a872a) }

var fileDescriptor_24f70eda5f2a872a = []byte{
	// 145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x48, 0xce, 0xcf, 0xc9,
	0x49, 0x4d, 0x2e, 0xc9, 0xcc, 0xcf, 0x8b, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x52, 0x22, 0xf9, 0x49, 0x59, 0xa9, 0xc9, 0x25,
	0xa8, 0x92, 0x4a, 0x96, 0x5c, 0x5c, 0xce, 0x70, 0x8d, 0x42, 0xda, 0x5c, 0xec, 0xc9, 0xf9, 0x79,
	0x25, 0xa9, 0x79, 0x25, 0x12, 0x8c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0x82, 0x10, 0x65, 0x7a, 0xfe,
	0x60, 0xbd, 0x9e, 0x25, 0xa9, 0xb9, 0x41, 0x30, 0x15, 0x4e, 0xea, 0x51, 0xaa, 0xc9, 0xf9, 0xb9,
	0x7a, 0x79, 0xa9, 0xa9, 0x05, 0xfa, 0xe9, 0xf9, 0x05, 0x39, 0x89, 0x25, 0x69, 0xf9, 0x45, 0xb9,
	0xfa, 0xa9, 0x89, 0xc5, 0x95, 0xb9, 0x45, 0xfa, 0xe9, 0x45, 0x05, 0xc9, 0xfa, 0x60, 0xcd, 0x49,
	0x6c, 0x60, 0xca, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x12, 0x2e, 0x3e, 0x34, 0xa3, 0x00, 0x00,
	0x00,
}
