// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mapreduce_message.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReqMRMsg struct {
	Handler              string            `protobuf:"bytes,1,opt,name=handler,proto3" json:"handler,omitempty"`
	Mapper               string            `protobuf:"bytes,2,opt,name=mapper,proto3" json:"mapper,omitempty"`
	Reducer              string            `protobuf:"bytes,3,opt,name=reducer,proto3" json:"reducer,omitempty"`
	Consumer             string            `protobuf:"bytes,4,opt,name=consumer,proto3" json:"consumer,omitempty"`
	Params               map[string]string `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Content              map[string][]byte `protobuf:"bytes,6,rep,name=content,proto3" json:"content,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ReqMRMsg) Reset()         { *m = ReqMRMsg{} }
func (m *ReqMRMsg) String() string { return proto.CompactTextString(m) }
func (*ReqMRMsg) ProtoMessage()    {}
func (*ReqMRMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a9e5f73dd22b64f, []int{0}
}

func (m *ReqMRMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqMRMsg.Unmarshal(m, b)
}
func (m *ReqMRMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqMRMsg.Marshal(b, m, deterministic)
}
func (m *ReqMRMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqMRMsg.Merge(m, src)
}
func (m *ReqMRMsg) XXX_Size() int {
	return xxx_messageInfo_ReqMRMsg.Size(m)
}
func (m *ReqMRMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqMRMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ReqMRMsg proto.InternalMessageInfo

func (m *ReqMRMsg) GetHandler() string {
	if m != nil {
		return m.Handler
	}
	return ""
}

func (m *ReqMRMsg) GetMapper() string {
	if m != nil {
		return m.Mapper
	}
	return ""
}

func (m *ReqMRMsg) GetReducer() string {
	if m != nil {
		return m.Reducer
	}
	return ""
}

func (m *ReqMRMsg) GetConsumer() string {
	if m != nil {
		return m.Consumer
	}
	return ""
}

func (m *ReqMRMsg) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *ReqMRMsg) GetContent() map[string][]byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type RespMRMsg struct {
	Result               map[string][]byte `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Success              bool              `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message              string            `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RespMRMsg) Reset()         { *m = RespMRMsg{} }
func (m *RespMRMsg) String() string { return proto.CompactTextString(m) }
func (*RespMRMsg) ProtoMessage()    {}
func (*RespMRMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a9e5f73dd22b64f, []int{1}
}

func (m *RespMRMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespMRMsg.Unmarshal(m, b)
}
func (m *RespMRMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespMRMsg.Marshal(b, m, deterministic)
}
func (m *RespMRMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespMRMsg.Merge(m, src)
}
func (m *RespMRMsg) XXX_Size() int {
	return xxx_messageInfo_RespMRMsg.Size(m)
}
func (m *RespMRMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_RespMRMsg.DiscardUnknown(m)
}

var xxx_messageInfo_RespMRMsg proto.InternalMessageInfo

func (m *RespMRMsg) GetResult() map[string][]byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *RespMRMsg) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RespMRMsg) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqMRMsg)(nil), "proto.ReqMRMsg")
	proto.RegisterMapType((map[string][]byte)(nil), "proto.ReqMRMsg.ContentEntry")
	proto.RegisterMapType((map[string]string)(nil), "proto.ReqMRMsg.ParamsEntry")
	proto.RegisterType((*RespMRMsg)(nil), "proto.RespMRMsg")
	proto.RegisterMapType((map[string][]byte)(nil), "proto.RespMRMsg.ResultEntry")
}

func init() { proto.RegisterFile("mapreduce_message.proto", fileDescriptor_5a9e5f73dd22b64f) }

var fileDescriptor_5a9e5f73dd22b64f = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0x4f, 0x4b, 0xc3, 0x30,
	0x14, 0xa7, 0x9b, 0xeb, 0xb6, 0xb7, 0x1d, 0x24, 0x88, 0x86, 0xe9, 0x61, 0x0c, 0xc4, 0x9d, 0x5a,
	0x70, 0x22, 0xba, 0xa3, 0xe2, 0x71, 0x20, 0x3d, 0x7a, 0x91, 0x98, 0x3d, 0x2b, 0xd8, 0x34, 0xf1,
	0xa5, 0x15, 0xf6, 0xad, 0xfc, 0x34, 0x7e, 0x1e, 0x69, 0x92, 0x4a, 0xd9, 0x45, 0x3c, 0xe5, 0xfd,
	0xf8, 0xfd, 0xe1, 0xf7, 0x5e, 0xe0, 0x44, 0x09, 0x43, 0xb8, 0xad, 0x25, 0x3e, 0x2b, 0xb4, 0x56,
	0xe4, 0x98, 0x18, 0xd2, 0x95, 0x66, 0x03, 0xf7, 0x2c, 0xbe, 0x7b, 0x30, 0xca, 0xf0, 0x63, 0x93,
	0x6d, 0x6c, 0xce, 0x38, 0x0c, 0xdf, 0x44, 0xb9, 0x2d, 0x90, 0x78, 0x34, 0x8f, 0x96, 0xe3, 0xac,
	0x85, 0xec, 0x18, 0x62, 0x25, 0x8c, 0x41, 0xe2, 0x3d, 0x47, 0x04, 0xd4, 0x38, 0x7c, 0x3a, 0xf1,
	0xbe, 0x77, 0x04, 0xc8, 0x66, 0x30, 0x92, 0xba, 0xb4, 0xb5, 0x42, 0xe2, 0x07, 0x8e, 0xfa, 0xc5,
	0x6c, 0x05, 0xb1, 0x11, 0x24, 0x94, 0xe5, 0x83, 0x79, 0x7f, 0x39, 0xb9, 0x3c, 0xf5, 0x9d, 0x92,
	0xb6, 0x48, 0xf2, 0xe8, 0xd8, 0x87, 0xb2, 0xa2, 0x5d, 0x16, 0xa4, 0xec, 0x1a, 0x86, 0x52, 0x97,
	0x15, 0x96, 0x15, 0x8f, 0x9d, 0xeb, 0x6c, 0xdf, 0x75, 0xef, 0x69, 0x6f, 0x6b, 0xc5, 0xb3, 0x5b,
	0x98, 0x74, 0xe2, 0xd8, 0x21, 0xf4, 0xdf, 0x71, 0x17, 0xf6, 0x6b, 0x46, 0x76, 0x04, 0x83, 0x4f,
	0x51, 0xd4, 0x18, 0x56, 0xf3, 0x60, 0xdd, 0xbb, 0x89, 0x66, 0x6b, 0x98, 0x76, 0x33, 0xff, 0xf2,
	0x4e, 0x3b, 0xde, 0xc5, 0x57, 0x04, 0xe3, 0x0c, 0xad, 0xf1, 0x97, 0xbd, 0x82, 0x98, 0xd0, 0xd6,
	0x45, 0xc5, 0xa3, 0xbd, 0xee, 0x41, 0xd1, 0x4c, 0x75, 0x11, 0xba, 0x07, 0x6d, 0x73, 0x5d, 0x5b,
	0x4b, 0x89, 0xd6, 0xba, 0xfc, 0x51, 0xd6, 0xc2, 0x86, 0x09, 0xdf, 0xd9, 0xde, 0x3d, 0xc0, 0x66,
	0xdd, 0x4e, 0xd4, 0x7f, 0x2a, 0xdf, 0x5d, 0x3c, 0x9d, 0x4b, 0xad, 0x92, 0x12, 0xd1, 0xa4, 0xb9,
	0x36, 0x85, 0xa8, 0x5e, 0x35, 0xa9, 0x14, 0x85, 0xdd, 0x29, 0x4a, 0x73, 0x32, 0x32, 0x75, 0xad,
	0x5f, 0x62, 0xf7, 0xac, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0xea, 0x54, 0xd1, 0xa6, 0x5d, 0x02,
	0x00, 0x00,
}
