// Code generated by protoc-gen-go. DO NOT EDIT.
// source: object_message.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ObjectItem struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectItem) Reset()         { *m = ObjectItem{} }
func (m *ObjectItem) String() string { return proto.CompactTextString(m) }
func (*ObjectItem) ProtoMessage()    {}
func (*ObjectItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_e914ab4db3771170, []int{0}
}

func (m *ObjectItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectItem.Unmarshal(m, b)
}
func (m *ObjectItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectItem.Marshal(b, m, deterministic)
}
func (m *ObjectItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectItem.Merge(m, src)
}
func (m *ObjectItem) XXX_Size() int {
	return xxx_messageInfo_ObjectItem.Size(m)
}
func (m *ObjectItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectItem.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectItem proto.InternalMessageInfo

func (m *ObjectItem) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ObjectItem) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*ObjectItem)(nil), "proto.ObjectItem")
}

func init() { proto.RegisterFile("object_message.proto", fileDescriptor_e914ab4db3771170) }

var fileDescriptor_e914ab4db3771170 = []byte{
	// 140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc9, 0x4f, 0xca, 0x4a,
	0x4d, 0x2e, 0x89, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0x05, 0x53, 0x4a, 0x56, 0x5c, 0x5c, 0xfe, 0x60, 0x69, 0xcf, 0x92, 0xd4, 0x5c, 0x21,
	0x21, 0x2e, 0x96, 0x92, 0xca, 0x82, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b,
	0x48, 0x82, 0x8b, 0x3d, 0x39, 0x3f, 0xaf, 0x24, 0x35, 0xaf, 0x44, 0x82, 0x49, 0x81, 0x51, 0x83,
	0x27, 0x08, 0xc6, 0x75, 0x52, 0x8f, 0x52, 0x4d, 0xce, 0xcf, 0xd5, 0xcb, 0x4b, 0x4d, 0x2d, 0xd0,
	0x4f, 0xcf, 0x2f, 0xc8, 0x49, 0x2c, 0x49, 0xcb, 0x2f, 0xca, 0xd5, 0x4f, 0x4d, 0x2c, 0xae, 0xcc,
	0x2d, 0xd2, 0x4f, 0x2f, 0x2a, 0x48, 0xd6, 0x07, 0x5b, 0x92, 0xc4, 0x06, 0xa6, 0x8c, 0x01, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x74, 0x11, 0x68, 0x8b, 0x8a, 0x00, 0x00, 0x00,
}
